// Generated by scripts/new-release-signing-key.ps1. The matching private key is never committed.
using InfiniTranseon.Contracts.Security;

namespace InfiniTranseon.App.Presentation.Services;

internal static class ProductionReleaseTrustRoot
{
    internal const string CurrentKeyId = "release-2026-b";

    internal static Ed25519TrustRootSet Create() => new(
        new Ed25519PublicKey(CurrentKeyId, Convert.FromHexString(
            "aa2905d589c750d78e49d8cb71b11f4d0e2a4478543c2ab5452cffe310241d88")),
        next: null,
        revokedKeyIds: []);
}
