// Generated by scripts/new-release-signing-key.ps1. The matching private key is never committed.
using InfiniTranseon.Contracts.Security;

namespace InfiniTranseon.App.Presentation.Services;

internal static class ProductionReleaseTrustRoot
{
    internal const string CurrentKeyId = "release-2026-a";

    internal static Ed25519TrustRootSet Create() => new(
        new Ed25519PublicKey(CurrentKeyId, Convert.FromHexString(
            "db371e9781ff844e42efcce8c7f7e161bfbf352adbbb32670abfd68a9e4502e7")),
        next: null,
        revokedKeyIds: []);
}