namespace InfiniTranseon.Contracts.Runtime;

public sealed record RuntimeCapabilities(
    int ProtocolVersion,
    int MaxCaptureSources,
    int MaxTargets,
    int MaxCaptureDimension,
    long MaxCapturePixelsPerSource,
    int MaxRegionsPerTarget,
    int MaxActiveTracksPerTarget,
    int MaxOcrBoxesPerResult,
    int MaxSourceChars,
    int MaxOverlayCharsPerTarget,
    int MaxTranslationChannelsPerRegion,
    int MaxOutstandingWgcFramesPerSource,
    int MaxOwnedFrameTexturesPerSource,
    int MaxReadbackCropsPerSource,
    long MaxReadbackPixelsPerSourceRing,
    long MaxGlobalOcrCropBytesInFlight,
    int MaxMappedReadbacksPerAdapter,
    int MaxMappedReadbackHoldMilliseconds,
    long MaxDetectionPyramidBytesPerSource,
    long MaxOverlaySurfaceBytesPerTarget,
    int MaxOcrSessions,
    long MaxOcrTensorWorkspaceBytes,
    long MaxEngineCommittedBytes,
    long MaxModelWorkerCommittedBytes,
    long MaxGpuBytesPerAdapterCeiling,
    int MaxGpuBudgetPercentage,
    int MaxIpcMessageBytes,
    long MaxIpcInFlightBytes,
    long MaxRecentTranslationBytes,
    long MaxTranslationCacheBytes,
    long MaxDatabasePageCacheBytes)
{
    public const long ModelWorkerCommittedBytesLimit = 8L * 1024 * 1024 * 1024;

    public static RuntimeCapabilities VersionOne { get; } = new(
        ProtocolVersion: 1,
        MaxCaptureSources: 8,
        MaxTargets: 8,
        MaxCaptureDimension: 8192,
        MaxCapturePixelsPerSource: 33_554_432,
        MaxRegionsPerTarget: 256,
        MaxActiveTracksPerTarget: 512,
        MaxOcrBoxesPerResult: 2048,
        MaxSourceChars: 4096,
        MaxOverlayCharsPerTarget: 16_384,
        MaxTranslationChannelsPerRegion: 4,
        MaxOutstandingWgcFramesPerSource: 3,
        MaxOwnedFrameTexturesPerSource: 2,
        MaxReadbackCropsPerSource: 8,
        MaxReadbackPixelsPerSourceRing: 8_388_608,
        MaxGlobalOcrCropBytesInFlight: 134_217_728,
        MaxMappedReadbacksPerAdapter: 2,
        MaxMappedReadbackHoldMilliseconds: 20,
        MaxDetectionPyramidBytesPerSource: 67_108_864,
        MaxOverlaySurfaceBytesPerTarget: 134_217_728,
        MaxOcrSessions: 4,
        MaxOcrTensorWorkspaceBytes: 268_435_456,
        MaxEngineCommittedBytes: 2_147_483_648,
        MaxModelWorkerCommittedBytes: ModelWorkerCommittedBytesLimit,
        MaxGpuBytesPerAdapterCeiling: 1_073_741_824,
        MaxGpuBudgetPercentage: 25,
        MaxIpcMessageBytes: 8_388_608,
        MaxIpcInFlightBytes: 33_554_432,
        MaxRecentTranslationBytes: 5_242_880,
        MaxTranslationCacheBytes: 536_870_912,
        MaxDatabasePageCacheBytes: 67_108_864);
}
