[CmdletBinding(SupportsShouldProcess)]
param(
    [string] $KeyId = ('release-' + [DateTime]::UtcNow.ToString('yyyy') + '-a'),
    [string] $OutputPath = (Join-Path $PSScriptRoot `
        '..\src\InfiniTranseon.App\Presentation\Services\ProductionReleaseTrustRoot.cs'),
    [string] $CredentialTarget = 'InfiniTranseon/ReleaseSigning/Ed25519'
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

if ($KeyId -notmatch '^[a-z0-9][a-z0-9._-]{2,63}$') {
    throw 'KeyId must contain 3-64 lowercase letters, digits, dots, underscores, or hyphens.'
}
$outputFullPath = [IO.Path]::GetFullPath($OutputPath)
if (Test-Path -LiteralPath $outputFullPath) {
    throw "Trust-root source already exists at '$outputFullPath'. Key rotation requires a staged current/next-key release and must not overwrite this file."
}

$openSslCandidates = @(
    (Join-Path $env:ProgramFiles 'Git\usr\bin\openssl.exe'),
    (Join-Path ${env:ProgramFiles(x86)} 'Git\usr\bin\openssl.exe')
)
$openSsl = $openSslCandidates |
    Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } |
    Select-Object -First 1
if ([string]::IsNullOrWhiteSpace($openSsl)) {
    throw 'OpenSSL from Git for Windows was not found.'
}

if (-not ('InfiniTranseon.ReleaseCredentialNative' -as [type])) {
    Add-Type -TypeDefinition @'
using System;
using System.Runtime.InteropServices;

namespace InfiniTranseon
{
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct ReleaseCredential
    {
        public uint Flags;
        public uint Type;
        [MarshalAs(UnmanagedType.LPWStr)]
        public string TargetName;
        [MarshalAs(UnmanagedType.LPWStr)]
        public string Comment;
        public System.Runtime.InteropServices.ComTypes.FILETIME LastWritten;
        public uint CredentialBlobSize;
        public IntPtr CredentialBlob;
        public uint Persist;
        public uint AttributeCount;
        public IntPtr Attributes;
        [MarshalAs(UnmanagedType.LPWStr)]
        public string TargetAlias;
        [MarshalAs(UnmanagedType.LPWStr)]
        public string UserName;
    }

    public static class ReleaseCredentialNative
    {
        [DllImport("advapi32.dll", EntryPoint = "CredWriteW", CharSet = CharSet.Unicode, SetLastError = true)]
        public static extern bool CredWrite(ref ReleaseCredential credential, uint flags);
    }
}
'@
}

$temporaryRoot = Join-Path $env:TEMP (
    'infini-release-key-' + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $temporaryRoot | Out-Null
$privateKeyPath = Join-Path $temporaryRoot 'release-ed25519.pem'
$publicKeyPath = Join-Path $temporaryRoot 'release-ed25519-public.der'
$privateBytes = $null
$credentialBlob = [IntPtr]::Zero
try {
    & $openSsl genpkey -algorithm Ed25519 -out $privateKeyPath
    if ($LASTEXITCODE -ne 0) { throw 'Ed25519 private-key generation failed.' }
    & $openSsl pkey -in $privateKeyPath -pubout -outform DER -out $publicKeyPath
    if ($LASTEXITCODE -ne 0) { throw 'Ed25519 public-key derivation failed.' }

    $privateBytes = [IO.File]::ReadAllBytes($privateKeyPath)
    $publicDer = [IO.File]::ReadAllBytes($publicKeyPath)
    $subjectPublicKeyInfoPrefix = [Convert]::FromHexString('302A300506032B6570032100')
    $validPrefix = $publicDer.Length -eq 44
    if ($validPrefix) {
        for ($index = 0; $index -lt $subjectPublicKeyInfoPrefix.Length; $index++) {
            if ($publicDer[$index] -ne $subjectPublicKeyInfoPrefix[$index]) {
                $validPrefix = $false
                break
            }
        }
    }
    if (-not $validPrefix) {
        throw 'OpenSSL returned an unexpected Ed25519 public-key encoding.'
    }
    [byte[]] $rawPublicKey = $publicDer[12..43]
    $publicKeyHex = [Convert]::ToHexString($rawPublicKey).ToLowerInvariant()

    if (-not $PSCmdlet.ShouldProcess(
            $CredentialTarget,
            'Store the Ed25519 private key in Windows Credential Manager')) {
        return
    }
    $credentialBlob = [Runtime.InteropServices.Marshal]::AllocCoTaskMem($privateBytes.Length)
    [Runtime.InteropServices.Marshal]::Copy(
        $privateBytes,
        0,
        $credentialBlob,
        $privateBytes.Length)
    $credential = [InfiniTranseon.ReleaseCredential]@{
        Flags = 0
        Type = 1
        TargetName = $CredentialTarget
        Comment = 'Infini-Transeon GitHub Release Ed25519 signing key'
        CredentialBlobSize = $privateBytes.Length
        CredentialBlob = $credentialBlob
        Persist = 2
        AttributeCount = 0
        Attributes = [IntPtr]::Zero
        TargetAlias = $null
        UserName = $KeyId
    }
    if (-not [InfiniTranseon.ReleaseCredentialNative]::CredWrite([ref]$credential, 0)) {
        $errorCode = [Runtime.InteropServices.Marshal]::GetLastWin32Error()
        throw "Windows Credential Manager rejected the release key (Win32 $errorCode)."
    }

    $source = @"
// Generated by scripts/new-release-signing-key.ps1. The matching private key is never committed.
using InfiniTranseon.Contracts.Security;

namespace InfiniTranseon.App.Presentation.Services;

internal static class ProductionReleaseTrustRoot
{
    internal const string CurrentKeyId = "$KeyId";

    internal static Ed25519TrustRootSet Create() => new(
        new Ed25519PublicKey(CurrentKeyId, Convert.FromHexString(
            "$publicKeyHex")),
        next: null,
        revokedKeyIds: []);
}
"@
    New-Item -ItemType Directory -Path (Split-Path -Parent $outputFullPath) -Force | Out-Null
    [IO.File]::WriteAllText(
        $outputFullPath,
        $source,
        [Text.UTF8Encoding]::new($false))

    [pscustomobject]@{
        KeyId = $KeyId
        PublicKeyHex = $publicKeyHex
        TrustRootSource = $outputFullPath
        CredentialTarget = $CredentialTarget
    }
}
finally {
    if ($credentialBlob -ne [IntPtr]::Zero) {
        for ($index = 0; $index -lt $privateBytes.Length; $index++) {
            [Runtime.InteropServices.Marshal]::WriteByte($credentialBlob, $index, 0)
        }
        [Runtime.InteropServices.Marshal]::FreeCoTaskMem($credentialBlob)
    }
    if ($null -ne $privateBytes) {
        [Array]::Clear($privateBytes, 0, $privateBytes.Length)
    }
    if (Test-Path -LiteralPath $temporaryRoot) {
        Remove-Item -LiteralPath $temporaryRoot -Recurse -Force
    }
}
